# Generated by Django 5.0.4 on 2024-05-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='devliveredAt',
            new_name='deliveredAt',
        ),
    ]
