# Generated by Django 5.0.4 on 2024-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_devliveredat_order_deliveredat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveredAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
