# Generated by Django 5.0.4 on 2024-05-13 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_order_deliveredat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveredAt',
        ),
        migrations.AddField(
            model_name='order',
            name='devliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
