# Generated by Django 5.0.4 on 2024-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_order_devliveredat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='devliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
