# Generated by Django 5.0.4 on 2024-05-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_order_devliveredat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='devliveredAt',
            new_name='deliveredAt',
        ),
    ]
